name: LovePolarityandPassion
favicon: null
layout_spectrum: 0.61571
typography_spectrum: 0.36052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f0'
    - '#a50010'
    - '#f7323b'
    - '#533c20'
    - '#a1622c'
  brandStrength: 0.6875
  lightness: 0.9114794004708529
  saturation: 0.5625
  rhythmicContrast: 0.9089873074553907
purpose: []
