name: LovePolarityandPassion
favicon: null
layout_spectrum: 0.6246644542552531
typography_spectrum: 0.09355571609921753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f1'
    - '#a60010'
    - '#f8333c'
    - '#f8bd9e'
    - '#835428'
  brandStrength: 0.6875
  lightness: 0.9114794004708529
  saturation: 0.5625
  rhythmicContrast: 0.9089873074553907
purpose: []
